{% set version = "0.28.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: pyshacl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshacl/pyshacl-{{ version }}.tar.gz
  sha256: d41d7a052f7a5311ae89f8357d7a7ba37a88362204eda93141556c588c6a3ff6

build:
  number: 0
  noarch: python
  script:
    # poetry puts stuff all over
    {% set remove_from_sp_dir = [
      "CHANGELOG.md",
      "CONTRIBUTING.md",
      "CONTRIBUTORS.md",
      "FEATURES.md",
      "LICENSE.txt",
      "README.md",
    ] %}
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
    - |-
      {{ PYTHON }} -c "import os, pathlib; sp = pathlib.Path(os.environ['SP_DIR']); [(sp / f).unlink() for f in {{ remove_from_sp_dir }}]"
  entry_points:
    - pyshacl = pyshacl.cli:main
    - pyshacl_rules = pyshacl.cli_rules:main
    - pyshacl_server = pyshacl.http:cli
    - pyshacl_validate = pyshacl.cli:main

requirements:
  host:
    - python >=3.8.1
    - pip
    - poetry-core >=1.8.1,<2
  run:
    - python >=3.8.1
    - importlib-metadata >6
    - owlrl >=6.0.2,<7
    - packaging >=21.3
    - prettytable >=3.7.0
    - rdflib-with-html >=6.3.2,<8

test:
  requires:
    - pip
  imports:
    - pyshacl
  commands:
    - pip check
    - pyshacl --help

outputs:
  - name: pyshacl

  - name: pyshacl-with-http
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
        - sanic >=22.12,<23
        - sanic-ext >=23.3,<23.6
        - sanic-cors ==2.2.0.*
    test:
      requires:
        - pip
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with http extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

  - name: pyshacl-with-js
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
        - pyduktape2 >=0.4.3,<0.5.0
    test:
      requires:
        - pip
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with js extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

  - name: pyshacl-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyshacl-with-http", max_pin="x.x.x") }}
        - {{ pin_subpackage("pyshacl-with-js", max_pin="x.x.x") }}
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
    test:
      source_files:
        - test
      requires:
        - pip
        - pytest-cov
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
        - coverage run --branch --source=pyshacl -m pytest -vv --color=yes --tb=long -k "not owl_imports"
        - coverage report --show-missing --skip-covered --fail-under=71
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with all extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  feedstock-name: pyshacl
  recipe-maintainers:
    - bollwyvl
    - satra
