{% set version = "0.22.2" %}

package:
  name: pyshacl-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshacl/pyshacl-{{ version }}.tar.gz
  sha256: a9cbba8048438410eca0ee437df2cc55612cf5ed14574dc9524713063d10d3e4

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

outputs:
  - name: pyshacl
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      entry_points:
        - pyshacl = pyshacl.cli:main
        - pyshacl_server = pyshacl.http:cli
        - pyshacl_validate = pyshacl.cli:main
    requirements:
      host:
        - pip
        - poetry-core >=1.5.2,<2
        - python >=3.7
      run:
        - html5lib >=1.1,<2
        - owlrl >=6.0.2,<7
        - packaging >=21.3
        - prettytable >=2.2.1,<3.0.0
        - python >=3.7
        - rdflib >=6.2.0,<7
    test:
      requires:
        - pip
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

  - name: pyshacl-with-http
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
        - python >=3.7
        - sanic >=22.12,<23
        - sanic-ext >=23.3,<23.6
        - sanic-cors ==2.2.0.*
    test:
      requires:
        - pip
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with http extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

  - name: pyshacl-with-js
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
        - python >=3.7
        - pyduktape2 >=0.4.1,<0.5.0
    test:
      requires:
        - pip
      imports:
        - pyshacl
      commands:
        - pip check
        - pyshacl --help
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with js extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

  - name: pyshacl-with-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pyshacl", max_pin="x.x.x") }}
        - {{ pin_subpackage("pyshacl-with-http", max_pin="x.x.x") }}
        - {{ pin_subpackage("pyshacl-with-js", max_pin="x.x.x") }}
        - python >=3.7
    test:
      source_files:
        - test
      requires:
        - pip
        - pytest-cov
      imports:
        - pyshacl
      commands:
        - python -m pip check
        - pyshacl --help
        - pytest -vv --cov-fail-under=77 --cov=pyshacl --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not owl_imports"
    about:
      home: https://github.com/RDFLib/pySHACL
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE.txt
      summary: A Python validator for SHACL (with all extra)
      description: |
        This is a pure Python module which allows for the validation of RDF graphs
        against Shapes Constraint Language (SHACL) graphs. This module uses the
        rdflib Python library for working with RDF and is dependent on the OWL-RL
        Python module for OWL2 RL Profile-based expansion of data graphs.

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  feedstock-name: pyshacl
  recipe-maintainers:
    - bollwyvl
    - satra
