{% set name = "pyshacl" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fc05e01734dbd3eb4211a6cecca55b225b284e7d7dd41a5649b76d57af11c79

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshacl = pyshacl.cli:main

requirements:
  host:
    - pip
    - poetry >=1.0.9
    - python >=3.6
  run:
    - owlrl >=5.2.1
    - python >=3.6
    - rdflib >=5.0.0
    - rdflib-jsonld >=0.5.0

test:
  source_files:
    - test
  requires:
    - pytest-cov
    - pip
  imports:
    - pyshacl
  commands:
    - python -m pip check
    - pyshacl --help
    - pytest --cov=pyshacl -k "not owl_imports" -vv

about:
  home: https://github.com/RDFLib/pySHACL
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Python validator for SHACL
  description: |
    This is a pure Python module which allows for the validation of RDF graphs
    against Shapes Constraint Language (SHACL) graphs. This module uses the
    rdflib Python library for working with RDF and is dependent on the OWL-RL
    Python module for OWL2 RL Profile-based expansion of data graphs.

extra:
  recipe-maintainers:
    - bollwyvl
    - satra
